apiVersion: v1
kind: Service
metadata:
  name: svc-mediawiki-web
  labels:
    run: svc-mediawiki-web
spec:
  type: NodePort
  selector:
    app: mediawiki-web
  ports:
  - protocol: TCP
    port: 30010
    nodePort: 30010
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mediawiki-sql
  labels:
    run: svc-mediawiki-sql
spec:
  selector:
    appdb: mediawiki-sql
  ports:
  - protocol: TCP
    port: 3306
